### ISSUE TITLE
Color of bond does not update when changing the color of the species

### ISSUE THREAD

**Issue by hanjiahe1999** [superstar54/weas-widget#74]
I used the viewer.avr.species.settings to define the color which I want to set.
But I find the bug is here.  In this picture, the bond between the Hydrogen and the Fluorine is error, it didn't change.
![image](https://github.com/user-attachments/assets/1e19a2e7-ad3e-433c-a545-f41ed5315d0a)

**Comment by hanjiahe1999** [comment]
![image](https://github.com/user-attachments/assets/74edc300-f3d5-48a5-acbe-3167c073f8df)

**Comment by superstar54** [comment]
Hi @hanjiahe1999 , thanks for reporting the issue.

For the moment, one need also update the settings of the bond.
```
from ase.build import molecule
from weas_widget import WeasWidget

atoms = molecule("CH4")
viewer = WeasWidget()
viewer.from_ase(atoms)
viewer.avr.species.settings["C"].update({"color": "blue"})
viewer.avr.bond.settings["[C, H]"].update({"color1": "blue"})
viewer.avr.model_style =1
viewer
```
![image](https://github.com/user-attachments/assets/e4e31528-a107-4ad5-a0c9-a22858001b99)

In some cases, the user may want a different bond color from the species. That's why the API for changing the bond's color is exit.

In case you want to update all bond settings automatically, you can run
```
# update bond's settings so that the species' color is used for the bonds.
viewer.avr.bond.update_atoms()
```

**Comment by hanjiahe1999** [comment]
Nice, Thank you for your reply！！！
